# -*- coding: utf-8 -*-
"""Laplacian filter .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oz_13Btbz2l9c-mqOHanQlXBLryFgmrP
"""

import cv2
import matplotlib.pyplot as plt
#Load the image:
source =cv2.imread('/content/I2.jpg',cv2.IMREAD_COLOR)
#//Remove noise by applying Gaussian Blur:
source =cv2.GaussianBlur(source,(3,3),0)
#//Here,first argument is the image. Second defines the kernel size.
#//Convert to grayscale:
source_gray =cv2.cvtColor(source,cv2.COLOR_BGR2GRAY)
#//ApplytheLaplacianFilter:
dest =cv2.Laplacian(source_gray,cv2.CV_16S,ksize=3)
abs_dest = cv2.convertScaleAbs(dest)
#//Show the output:
plt.imshow(abs_dest,cmap="gray")

import cv2
import matplotlib.pyplot as plt
#Load the image:
source =cv2.imread('/content/I3.jpg',cv2.IMREAD_COLOR)
#//Remove noise by applying Gaussian Blur:
source =cv2.GaussianBlur(source,(3,3),0)
#//Here,first argument is the image. Second defines the kernel size.
#//Convert to grayscale:
source_gray =cv2.cvtColor(source,cv2.COLOR_BGR2GRAY)
#//ApplytheLaplacianFilter:
dest =cv2.Laplacian(source_gray,cv2.CV_16S,ksize=3)
abs_dest = cv2.convertScaleAbs(dest)
#//Show the output:
plt.imshow(abs_dest,cmap="gray")

import cv2
import matplotlib.pyplot as plt
#Load the image:
source =cv2.imread('/content/I4.jpg',cv2.IMREAD_COLOR)
#//Remove noise by applying Gaussian Blur:
source =cv2.GaussianBlur(source,(3,3),0)
#//Here,first argument is the image. Second defines the kernel size.
#//Convert to grayscale:
source_gray =cv2.cvtColor(source,cv2.COLOR_BGR2GRAY)
#//ApplytheLaplacianFilter:
dest =cv2.Laplacian(source_gray,cv2.CV_16S,ksize=3)
abs_dest = cv2.convertScaleAbs(dest)
#//Show the output:
plt.imshow(abs_dest,cmap="gray")